site_name: ZHU Documents
site_url: https://jivebiscuit.github.io
repo_url: https://github.com/jivebiscuit/jivebiscuit.github.io
repo_name: jivebiscuit.github.io
edit_uri: edit/main/docs/

theme:
  name: material
  font:
    text: Inter
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips
    - toc.follow
    - content.action.edit

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil

plugins:
  - search
  - awesome-nav

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      toc_depth: 3
  - attr_list

extra_css:
  - stylesheets/extra.css