site_name: vZHU Resources
site_url: https://jivebiscuit.github.io

theme:
  name: material
  palette: 

  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences