nav:
    - Docs Home: index.md
    - Policies:
      - policy/general.md
      - policy/events.md
      - policy/training.md
      - Training:
        - policy/training-syllabus.md
    - SOPs:
      - General:
        - General Control: sop/general-control-sop.md
      - Enroute:
        - ZHU: sop/enroute-sop.md
      - TRACON:
        - I90: sop/i90-sop.md
      - Airports:
        - AUS: sop/aus-sop.md
        - CRP: sop/crp-sop.md
        - HOU: sop/hou-sop.md
        - IAH: sop/iah-sop.md
        - MSY: sop/msy-sop.md
        - SAT: sop/sat-sop.md
    - LOA: loa
    - QRC: qrc
    - NOTAC:
      - notac/vatis4-1.md
    - Guides:
      - guides/teamspeak.md
      - guides/crc-getting-started.md
      - guides/crc-voice.md


